dependent_repositories:
- name: kogito-runtimes
  branch: 1.6.x
- name: kogito-apps
  branch: 1.6.x
- name: kogito-examples
  branch: 1.6.x
- name: kogito-images
  branch: 1.6.x
- name: kogito-operator
  branch: 1.6.x
- name: rhpam-kogito-operator
  branch: 1.6.x
- name: optaplanner
  branch: 8.6.x
