generation_config:
  missing_environment: ignore
job_types:
  nightly:
    disabled: true
  other:
    disabled: true
environments:
  native:
    env_vars:
      NATIVE: true
      BUILD_MVN_OPTS_CURRENT: -Dnative -Dquarkus.native.container-build=true
      ADDITIONAL_TIMEOUT: 720
    ids:
    - native
  sonarcloud:
    auto_generation: false
    env_vars:
      ENABLE_SONARCLOUD: true
    ids:
    - sonarcloud
    - coverage
  ecosystem:
    auto_generation: false
    ids:
    - ecosystem
disable:
  images-deploy: false
repositories:
- name: incubator-kie-kogito-pipelines
  job_display_name: kogito-pipelines
  branch: 2.2.x
  is_branch_config_repo: true
- name: incubator-kie-kogito-runtimes
  job_display_name: kogito-runtimes
  branch: 2.2.x
- name: incubator-kie-kogito-apps
  job_display_name: kogito-apps
  branch: 2.2.x
- name: incubator-kie-kogito-examples
  job_display_name: kogito-examples
  branch: 2.2.x
- name: incubator-kie-kogito-docs
  job_display_name: kogito-docs
  branch: 2.2.x
git:
  author:
    name: apache
    credentials_id: 399061d0-5ab5-4142-a186-a52081fef742
    token_credentials_id: kie-ci3-token
    push:
      credentials_id: 84811880-2025-45b6-a44c-2f33bef30ad2
      token_credentials_id: 41128c14-bb63-4708-9074-d20a318ee630
  fork_author:
    name: kie-ci
    credentials_id: kie-ci
    push:
      credentials_id: kie-ci
  quarkus:
    author:
      name: quarkusio
      credentials_id: kie-ci
    branch: main
  jenkins_config_path: .ci/jenkins
buildchain_config:
  git:
    repository: incubator-kie-kogito-pipelines
    file_path: .ci/pull-request-config.yaml
    token_credentials_id: kie-ci3-token
maven:
  settings:
    nightly:
      config_file_id: kie-nightly-settings
    release:
      config_file_id: kie-release-settings
  nexus:
    release_url: TO_DEFINE
    release_repository: TO_DEFINE
    staging_profile_url: TO_DEFINE
    staging_profile_id: TO_DEFINE
    build_promotion_profile_id: TO_DEFINE
  artifacts_repository: ''
  artifacts_upload_repository:
    nightly:
      url: https://repository.apache.org/content/repositories/snapshots
      creds_id: apache-nexus-kie-deploy-credentials
    release:
      url: https://repository.apache.org/service/local/staging/deploy/maven2
      creds_id: jenkins-deploy-to-nexus-staging
  quarkus_platform_repository:
    url: TO_DEFINE
    creds_id: TO_DEFINE
cloud:
  image:
    registry_user_credentials_id: DOCKERHUB_USER
    registry_token_credentials_id: DOCKERHUB_TOKEN
    registry: docker.io
    namespace: apache
    latest_git_branch: main
release:
  gpg:
    sign:
      key_credentials_id: GPG_KEY_FILE
      passphrase_credentials_id: ''
  svn:
    staging_repository: https://dist.apache.org/repos/dist/dev/incubator/kie
    credentials_id: kie-dist-acct
jenkins:
  email_creds_id: KOGITO_CI_NOTIFICATION_EMAILS
  agent:
    docker:
      builder:
        image: docker.io/apache/incubator-kie-kogito-ci-build:main-latest
        args: --privileged --group-add docker
  default_tools:
    jdk: jdk_17_latest
    maven: maven_3.9.3
    sonar_jdk: jdk_17_latest
  jobs_definition_file: .ci/jenkins/dsl/jobs.groovy
